version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    restart: always
    ports:
      - '80:8000'
    tty: true
    volumes:
      - $PWD:/home
  db:
      image: mysql:latest
#      restart: always
      hostname: db
      container_name: db
      environment:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - ${MYSQL_VOLUME}:/var/lib/mysql
      ports:
        - "3306:3306"
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - '6379:6379'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 193.168.0.0/16
