"""create table poluente_scrap

Revision ID: 27691f7c4778
Revises: dc0c714ec0a8
Create Date: 2023-07-03 22:32:35.060949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27691f7c4778'
down_revision = 'dc0c714ec0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poluente_scrap',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('i_rede', sa.Unicode(length=50), nullable=True),
    sa.Column('data_inicial', sa.DateTime(), nullable=True),
    sa.Column('data_final', sa.DateTime(), nullable=True),
    sa.Column('i_tipo_dado', sa.Unicode(length=2), nullable=True),
    sa.Column('estacao', sa.Integer(), nullable=True),
    sa.Column('parametro', sa.Integer(), nullable=True),
    sa.Column('file', sa.Unicode(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poluente_scrap')
    # ### end Alembic commands ###
