"""create status column

Revision ID: 301692715a1a
Revises: 27691f7c4778
Create Date: 2023-07-05 21:52:38.316993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '301692715a1a'
down_revision = '27691f7c4778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poluente_scrap', sa.Column('status', sa.Unicode(length=50), nullable=True))
    op.create_unique_constraint('uq_poluente_scrap',
                                'poluente_scrap',
                                ['i_rede', 'data_inicial', 'data_inicial', 'data_final', 'i_tipo_dado', 'estacao','parametro'],
                                schema='datasaude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poluente_scrap', 'status')
    op.drop_constraint('uq_poluente_scrap', 'poluente_scrap', schema='datasaude')

    # ### end Alembic commands ###
