"""criar poluente table

Revision ID: dc0c714ec0a8
Revises: 005ce6e94401
Create Date: 2023-06-13 22:47:15.738141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc0c714ec0a8'
down_revision = '005ce6e94401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poluente',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Unicode(length=255), nullable=True),
    sa.Column('data_atual', sa.DateTime(), nullable=True),
    sa.Column('endereco', sa.Unicode(length=255), nullable=True),
    sa.Column('indice', sa.Integer(), nullable=True),
    sa.Column('municipio', sa.Unicode(length=50), nullable=True),
    sa.Column('nome', sa.Unicode(length=50), nullable=True),
    sa.Column('poluente', sa.Unicode(length=50), nullable=True),
    sa.Column('qualidade', sa.Unicode(length=50), nullable=True),
    sa.Column('situacao_rede', sa.Unicode(length=50), nullable=True),
    sa.Column('tipo_rede', sa.Unicode(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poluente')
    # ### end Alembic commands ###
